package com.persoff68.fatodo.model.constant;

public enum WsEventType {

    CONTACT_REQUEST_INCOMING,
    CONTACT_REQUEST_OUTCOMING,
    CONTACT_ACCEPT_INCOMING,
    CONTACT_ACCEPT_OUTCOMING,
    CONTACT_DELETE_INCOMING,
    CONTACT_DELETE_OUTCOMING,
    CONTACT_DELETE,

}
